### ISSUE TITLE
Domotizzazione e creazione di dispositivi fisici

### ISSUE THREAD

**Issue by vongomben** [sunnyvale-it/chieri-calendari-raccolta-rifiuti#30]
Progetto molto interessante. 
Metto a disposizione il mio percorso di IoT e IoT Edge per la realizzazione di uno o più prototipi Calendar (o altri dati disponibili) ready. 
Se volete un vostro rappresentante può venire a lezione a presentare il progetto. Altrimenti sono disponibile ad un incontro anche solo io. 

Bravi e a presto

**Comment by denismaggior8** [comment]
Ciao Davide, 
scusa il ritardo ma sono giorni di fuoco. 
Grazie per l'apprezzamento, ci sentiamo al tel così mi spieghi cos'avevi in mente? Mandami il tuo num di cell sulla mail di ITS che ti chiamo in settimana.
