### ISSUE TITLE
Assenza notifiche eventi

### ISSUE THREAD

**Issue by MatteoMarabese** [sunnyvale-it/chieri-calendari-raccolta-rifiuti#5]
Attualmente non è presente un sistema di notifiche automatico.
Sarebbe utile predisporlo in maniera tale da avere un avviso almeno 12 ore prima.
In questo modo si ha la possibilità di sapere il giorno prima quale tipologia di rifiuto verrà ritirata l'indomani.
Attualmente, se si vuole impostare una notifica, è necessario farlo per ogni evento del calendario.

Grazie

**Comment by denismaggior8** [comment]
Funzionalità attualmente in sviluppo

**Comment by denismaggior8** [comment]
Funzionalità implementata sui calendari in formato ICS presenti sul branch master, è necessario reimportare il calendario per avere le notifiche
